### PR TITLE
README.md

### PR DESCRIPTION
**Pull request by NZCommanderPRO**

### CODE REVIEW

**Comment by NZCommanderPRO** [comment]
Close

**Comment by NZCommanderPRO** [comment]
gh repo clone NZCommanderPRO/TT4_Group2

**Comment by NZCommanderPRO** [comment]
Duplicate of #

**Comment by NZCommanderPRO** [comment]
#4

**Review by melvincwng — APPROVED** [review]
Revised the PR - and approved the changes.

**Pull request merged**
